# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-11-12 00:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('snack_id', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='编号')),
                ('title', models.CharField(max_length=20, unique=True, verbose_name='名称')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='定价')),
                ('market_price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='售价')),
                ('repertory', models.IntegerField(verbose_name='库存')),
                ('supplier', models.CharField(max_length=50, verbose_name='供货商')),
                ('invest_money', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='投资金额')),
                ('sell_number', models.IntegerField(default=0, verbose_name='售出数量')),
                ('img', models.ImageField(upload_to='static/imgs/snacks', verbose_name='图片')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('mod_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('products_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.ProductsType')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品',
                'db_table': 'products',
            },
        ),
    ]
