# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-11-12 23:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_productstype_page'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='snack_id',
            new_name='id',
        ),
    ]
