# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-11-14 20:00
from __future__ import unicode_literals

from django.db import migrations, models
import index.models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_auto_20191112_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='info',
            field=models.CharField(default=index.models.default_info, max_length=300, verbose_name='商品描述'),
        ),
    ]
